### ISSUE TITLE
Too much parrallelism creates issues with Grant: tuple concurrently updated

### ISSUE THREAD

**Issue by awoimbee** [pulumi/pulumi-postgresql#126]
I'm using my pulumi to configure a local postgreSQL instance, it's really fast !
Maybe it's a bit too fast. I get `error: could not execute revoke query: pq: tuple concurrently updated`.
To fix the issue, I need to run pulumi with low parallelism (e.g. `pulumi up -p 2`).

## Steps to reproduce
My stack is quite complex, it seems like is happens when it creates multiple `Grant` (one for a database, another for a schema, ...) to one `Role`. (to improve)

Expected: everything works
Actual: error is created, pulumi stops creating resources

## Environment
- postgreSQL: latest version, in docker
- CPU: 8 cores, 16 threads (R7 4800H)
- `pulumi`: `v3.28.0`
- `@pulumi/postgresql`: `3.4.0`

=> upstream issue: https://github.com/cyrilgdn/terraform-provider-postgresql/issues/178

**Comment by stack72** [comment]
Hi @awoimbee 

Please can you try and give us some minimal reproducible code that will help us here?

Paul

**Comment by shousper** [comment]
Looks like this issue still hasn't been resolved downstream: https://github.com/cyrilgdn/terraform-provider-postgresql/issues/178

**Comment by AaronFriel** [comment]
It looks like there is an upstream fix:
- https://github.com/cyrilgdn/terraform-provider-postgresql/pull/224
 
However it breaks compatibility with CockroachDB, one of our partners: 
- https://github.com/cyrilgdn/terraform-provider-postgresql/issues/277

I've requested advice from Cockroach here:
- https://github.com/cockroachdb/cockroach/issues/13546

**Comment by AaronFriel** [comment]
Hey @awoimbee, @shousper, we've made the decision to merge this despite #178, in order to bring this fix to users. Please let us know if you still encounter this with default parallelism.

**Comment by awoimbee** [comment]
I just tested against a local PG DB, a case where I would get tons of failures, it's working great ! Thanks !
