### ISSUE TITLE
Configure Provider to use TLS certificates in memory

### ISSUE THREAD

**Issue by KaoruDev** [pulumi/pulumi-postgresql#150]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
The Provider expects `sslrootcert`, `clientcert.cert`, and `clientcert.key` to be files. This is less than ideal because if I have the certificates in memory, I have to write them out to files as plaintext, exposing sensitive data, before I can create a provider. Ideally, I'd like to do something like this:

```typescript
// @pulumi/gcp provider
const sslCert = new classicSql.SslCert( 
  "ssl-cert",
  {
    commonName: `pulumi-${pulumi.getStack()}`,
    project: this.projectId,
    instance: this.instance.name,
  },
  { parent: this }
);

const pgProvider = new pg.Provider(
  "pg-provider",
  {
    clientcert: {
      key: sslCert.privateKey
      cert: sslCert.cert
    },
    sslrootcert: sslCert.serverCaCert,
  }
);
```

### Affected area/feature
Note sure, the Provider?

**Comment by guineveresaenger** [comment]
Hi @KaoruDev - I fully agree with you here but am really not sure that we can put this on the current roadmap for our team.

**Comment by KaoruDev** [comment]
Is it because this is a Pulumi version of the TF provider?

**Comment by gunar** [comment]
Same here. Documenting it might be a step forward — was hard to figure out what was going wrong from the error message. Now I see it expects a filename, which makes more sense.

**Comment by gunar** [comment]
@guineveresaenger What would be the most ergonomic way of writing OPS's `sslCert` into a file for `Provider` to consume? I was thinking `fs.writeFile` but maybe I should be using [`Command`](https://www.pulumi.com/registry/packages/command/api-docs/local/command/)?

@KaoruDev How did you solve it?

**Comment by gunar** [comment]
Terraform is just passing those arguments to it's Postgres client:

https://github.com/cyrilgdn/terraform-provider-postgresql/blob/04da94562ed88d479c3749afd14d594058f2fb99/postgresql/config.go#L212-L213

so I find it very unlikely that they'll build this mechanism just for us.

**Comment by gunar** [comment]
Also, couldn't hack my way using `fs.writeFile` or anything given that the certificate's body are generated during runtime, and I can't pass `Output<string>` into `fs.writeFile`.

@guineveresaenger maybe we can get some internal Pulumi expert to take a look and suggest a possible Pulumi-specific workaround?

**Comment by gunar** [comment]
## Update: I've done it!

```ts
  // XXX: In-memory certs are not supported so the workaround is to write the them to the local filesystem. It's not a perfect solution but given that the Client SSL Certificates act as a second-factor authentication, it's not too bad if the file gets exposed as to access the database we still need to provide a valid username/password pair.
  // https://github.com/pulumi/pulumi-postgresql/issues/150
  const tmpDir = await fs.mkdtemp(`${os.tmpdir()}${path.sep}`);
  const certPath = path.join(tmpDir, "cert.pem");
  const keyPath = path.join(tmpDir, "cert.key");
  pulumi
    .all([clientCert.cert, clientCert.privateKey])
    .apply(async ([cert, key]) => {
      console.log({ certPath, keyPath });
      await fs.writeFile(certPath, cert, { mode: 0o600 });
      await fs.writeFile(keyPath, key, { mode: 0o600 });
    });
  // …
    clientCert: {
      cert: certPath,
      key: keyPath,
    },
  // …
```

![image](https://user-images.githubusercontent.com/7684574/184446634-46b4a6ef-b089-439c-86f3-c84692b3a5a9.png)

**Comment by NinoFloris** [comment]
An issue with having full paths in the outputs is that pulumi commands like refresh fail to work if they can't find the path anymore (this can also happen because it's run from a different machine). Maybe relative paths work but I'm not sure what the working directory would be.

**Comment by gunar** [comment]
You're right. That's annoying. I guess it wouldn't be the end of the world to commit these SSL Certificates to the git repository, given that without the username/password pair they're useless.

Alternatively, in Google Cloud you might be able to use `cloud_sql_proxy` instead of Client SSL Certificates. But you'll need to spawn the proxy's process, which speaks to (1) having a deployment script (bash) which could pull the certificates from a stack's output and then would spawn `pulumi up` or (2) lifecycle hooks (re: https://github.com/pulumi/pulumi/issues/1691).

**Comment by AaronFriel** [comment]
Hey folks, sorry to see there hasn't been much progress. Please upvote the upstream issue here or let the maintainers know that this would be a priority for you:
- https://github.com/cyrilgdn/terraform-provider-postgresql/issues/253

We're happy to track upstream here, and we try not to diverge too much on behavior.
