### ISSUE TITLE
Feature request: Subscriptions

### ISSUE THREAD

**Issue by gunar** [pulumi/pulumi-postgresql#160]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The `pulumi-postgresql` package [already supports Publications](https://www.pulumi.com/registry/packages/postgresql/api-docs/publication). It'd be useful to have it support [Subscriptions](https://www.postgresql.org/docs/current/logical-replication-subscription.html) as well.

### Affected area/feature

I'm not sure.

**Comment by guineveresaenger** [comment]
Hi @gunar - 

We will bring this feature into this provider as soon as it is available in the upstream Terraform.

**Comment by gunar** [comment]
I've opened an issue: https://github.com/cyrilgdn/terraform-provider-postgresql/issues/238

**Comment by gunar** [comment]
This has now been released upstream: https://registry.terraform.io/providers/cyrilgdn/postgresql/1.18.0

Can we cut a new release that includes it?
