### ISSUE TITLE
gcp.sql.User() to allow setting the `REPLICATION` permission

### ISSUE THREAD

**Issue by gunar** [pulumi/pulumi-postgresql#166]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Today, you can give a user the `REPLICATION` permission with this query:

```sql
ALTER USER <user> REPLICATION;
```

This is necessary in order to allow said user to create a subscription in the database.

However, currently there's no way to do it using this library.

Can we add it this functionality?

### Affected area/feature

`pulumi-postgresql`

**Comment by danielrbradley** [comment]
Hi @gunar thanks for writing up the request.

I'm not too familiar with this provider, and I don't currently see a "User" resource [within the documentation](https://www.pulumi.com/registry/packages/postgresql/api-docs/#resources). There is a role resource which appears to have a `replication` property similar to what you're describing.

Similarly, the [upsteam terraform provider](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest/docs), from which this is bridged, doesn't appear to have a user resource either.

Are you requesting adding a `User` resource to the provider, which then should have a `replication` property?

Any changes such as these would require being supported in the [upstream terraform provider](https://github.com/cyrilgdn/terraform-provider-postgresql) before we could pull them into the Pulumi provider, so it might be worth also raising this there.

**Comment by gunar** [comment]
Thank you for the links @danielrbradley. It seems `ALTER USER` and `ALTER ROLE` are aliases (ie do the same thing), so I _should_ be able to implement this using [`gcp.sql.Role`](https://www.pulumi.com/registry/packages/postgresql/api-docs/role/#replication_nodejs) which has a `replication` field. Thanks for now—I'll reopen the issue if I have further questions/problems.
