### ISSUE TITLE
Dynamic Configuration Using a Stack's Output

### ISSUE THREAD

**Issue by BrunoRoque06** [pulumi/pulumi-postgresql#23]
Can we dynamically configure (e.g. `postgresql:host`, `postgresql:username`, `postgresql:password`) using a stack's output?

We have the following 2 projects:

```
azure-postgres/
postgres/
```

In `azure-postgres/index.ts` we have something like:

```typescript
import * as azure from "@pulumi/azure";
const server = new azure.postgresql.Server("pg-server", { ... });
export const serverFqdn = server.fqdn;
export const serverLogin = server.administratorLogin;
export const serverPassword = server.administratorLoginPassword;
```

In `postgres/Pulumi.dev.yaml` we have the following configuration hardcoded: 

```yaml
config:
  postgresql:host: <fqdn>
  postgresql:username: <login>
  postgresql:password: <pw>
```

How can we redirect the output of `azure-postgres/`'s stack to `postgres/` configuration? Is it possible? Thank you.

**Comment by pgavlin** [comment]
You can use `pulumi.StackReference` to achieve this in code: https://www.pulumi.com/docs/intro/concepts/organizing-stacks-projects/#inter-stack-dependencies

**Comment by BrunoRoque06** [comment]
Got it! Completely missed the `postgresql.Provider` class. Thank you.
