### ISSUE TITLE
DefaultPrivileges false-positive diff update

### ISSUE THREAD

**Issue by sylver** [pulumi/pulumi-postgresql#72]
# Current behavior

From a simple `DefaultPrivileges` instance : 
```js
new postgresql.DefaultPrivileges('test-grant', {
  database: 'dbname',
  objectType: 'table',
  privileges: ['ALL'],
  owner: 'foobar',
  role: 'foobar',
  schema: 'public',
})
```

It gets successfully created a the first `update` but then pulumi wants to update it at every subsequent run : 
```
~      └─ postgresql:index:DefaultPrivileges  test-grant  update     [diff: ~privileges]
```

I could try to provide a test repo if needed, but that's pretty much it here.
(I'm using the bitnami postgresql-ha helm chart to deploy the server the provider is bound to)

Maybe there's a way to see what the diff is about, but I don't know how (`-v` does not seem to have any effect on the output).

# Expected behavior

It should not detect any diff from the code above and not update at every `pulumi update`

# Version

pulumi version: 2.4.0
package version : 2.3.0

**Comment by stack72** [comment]
Hi @sylver 

Sorry that you are facing this issue - please can you post the diff (from the details) when you run a Pulumi up and it asks you y/n/d)

Thanks

Paul

**Comment by sylver** [comment]
Hi @stack72,

Not sure what you're asking here, since I already posted the relevant line (that's the only update).

Anyway, I inspected the resource in the pulumi state and the argument `privileges: ['ALL']` seems to have been transformed to `privileges: [
        'UPDATE',
        'REFERENCES',
        'TRUNCATE',
        'SELECT',
        'DELETE',
        'TRIGGER',
        'INSERT'
      ]`

And indeed, if I replace `privileges: ['ALL']` in my code with 
```
privileges: [
  'UPDATE',
  'REFERENCES',
  'TRUNCATE',
  'SELECT',
  'DELETE',
  'TRIGGER',
  'INSERT',
],
```
pulumi does not detect a diff anymore.

So the problem seems to reside here, with the special `'ALL'` argument converted explicitely to all the related privileges in the state and then triggering a diff at each run.

**Comment by stack72** [comment]
Hi @sylver 

This helps a lot. When you do `pulumi up` it will offer you the change to say `yes`, `no'` or `details`. I was asking for the details view - but this helps a lot

thanks

Paul

**Comment by sylver** [comment]
@stack72 

Oh ok, gotcha ! Sorry I didn't understand what you were asking, I literally never use it (though now I will 😅 ).

That indeed confirms what I was guessing : 
```
          ~ privileges: [
              ~ [0]: "UPDATE" => "ALL"
              - [1]: "REFERENCES"
              - [2]: "TRUNCATE"
              - [3]: "SELECT"
              - [4]: "DELETE"
              - [5]: "TRIGGER"
              - [6]: "INSERT"
            ]
```

**Comment by unthought** [comment]
FYI, I face the same issue with grant. In my case it's that the grant only contains `privileges: ["SELECT"]`, but it always detects a phantom change.

Postgresql 10.11 (AWS Aurora).

Diff: 

```
              ~ privileges: [
                  + [0]: "SELECT"
                ]
```

(this was literally running `pulumi up` after it just completed.
