### ISSUE TITLE
Ability to use postgres credentials from code

### ISSUE THREAD

**Issue by akhanqi** [pulumi/pulumi-postgresql#81]
I'm reading docs to setup pg credentials https://www.pulumi.com/docs/intro/cloud-providers/postgresql/setup/#configuring-credentials
and there are only two ways: env vars and pulumi config. Is there way to create database, providing credentials just in code? through resource options or something like that.

My case is to create multiple database instances, and multiple databases within one stack but with different credentials

**Comment by stack72** [comment]
Hi @akhanqi 

Yes, you can specify a list of providers and pass the username and password to them

Then you can target a database creation to a specific provider

Try this for some example on how to do this - https://www.pulumi.com/blog/controlling-aws-costs-with-lambda-and-pulumi/#deploying-to-multiple-regions

Hope this helps

Paul

**Comment by RXminuS** [comment]
Doesn't work when the certificates are generated in code though

**Comment by jazzdan** [comment]
Here's how I got this to work:

```typescript
const graphql_db = new aws.rds.Instance(
  "graphql-db",
);

graphql_db.endpoint.apply(endpoint => {
  const [host, portNum] = endpoint.split(":");
  const port = parseInt(portNum, 10);
  const provider: psql.Provider = new psql.Provider("psql", {
    database: "postgres",
    username: "root",
    password: config.requireSecret("root"),
    superuser: false,
    host,
    port,
  });
```
