### ISSUE TITLE
[Grant] Missing `object_type` argument option 'schema'

### ISSUE THREAD

**Issue by sylver** [pulumi/pulumi-postgresql#99]
# Current behavior

In the terraform provider, [`postgresql_grant`](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest/docs/resources/postgresql_grant) argument [`object_type`](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest/docs/resources/postgresql_grant#object_type) possible values are :

> The PostgreSQL object type to grant the privileges on (one of: database, schema, table, sequence,function).

But here, the [`Grant`](https://github.com/pulumi/pulumi-postgresql/blob/master/sdk/nodejs/grant.ts) `CustomResource` argument [`objectType`](https://github.com/pulumi/pulumi-postgresql/blob/cb4a1ec4d7d68dedb4a4c147134f1e3a083c3592/sdk/nodejs/grant.ts#L171) possible values are :

> The PostgreSQL object type to grant the privileges on (one of: database, table, sequence,function)

The `schema` option is missing.

# Expected behavior

`Grant` should reflect the same arguments and options as in the terraform provider.  
We should be able to set privileges on the `schema` object type with it.

Fixing this would also probably resolve  #88 

# Version

`pulumi` version: `2.17.2`
`@pulumi/postgresql` version : `2.5.3`

# Comments

I would have tried to submit a PR here, but all the code in this repo seems to be generated and I'm not sure where the generator is nor how it works, so I'm kind of at a loss here.  
Let me know if I can help by helping me figuring out how all the under the hood stuff works.

Thanks

**Comment by leezen** [comment]
It appears that this provider has moved to github.com/cyrilgdn/terraform-provider-postgresql while we are still pointing at github.com/terraform-providers/terraform-provider-postgresql

**Comment by sylver** [comment]
Indeed @leezen, I didn't notice that !

Do you think you can plan to update it soon ? Any chance I can help on this one if you guys are busy ?

Thanks

**Comment by stack72** [comment]
Hi @sylver 

My apologies - this slipped through - I am going to fix this up now!

Paul
